# Generated by Django 3.2 on 2021-06-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Desserts', 'Desserts'), ('Espresso', 'Espresso'), ('Drinks', 'Drinks'), ('Wraps', 'Wraps'), ('cake', 'Cake'), ('Specials', 'specials')], max_length=200, null=True),
        ),
    ]
